### ISSUE TITLE
Allow spaces around language name in code 

### ISSUE THREAD

**Issue by r0mflip** [WebReflection/lightdown#1]
It would be nice to have the ability to specify language as on GitHub's markdown, having spaces around the language would work on GitHub.

If I have ` ```<space>js `, the language detection works, it works on GitHub and most people might be used to it.

Allowing spaces on [this line](https://github.com/WebReflection/lightdown/blob/1a6aea1a9b32b2ff827fb613447b10cfb8a25926/index.js#L34) would be helpful 😇

**Comment by WebReflection** [comment]
why do you need spaces, if I might ask?

```js
console.log(
  'I just wrote ``js without spaces'
);
```

That would produce the expected result, no?
